image:
  repository: 113504009718.dkr.ecr.us-east-1.amazonaws.com/ecr-repo-django-app
  tag: latest
#  pullPolicy: IfNotPresent
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilization: 70

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

ingress:
  enabled: false
#  className: nginx
#  host: django.example.com
#  path: /
#  pathType: Prefix
#  tls: true

config:
  POSTGRES_PORT: 5432
  POSTGRES_HOST: postgres
  POSTGRES_USER: django_user
  POSTGRES_DB: django_db
  POSTGRES_PASSWORD: pas48159cf
  ALLOWED_HOSTS: localhost,.us-east-1.elb.amazonaws.com

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        postgresPassword: pas48159cf
        username: django_user
        database: django_db
        password: pas48159cf
  primary:
    persistence:
      size: 2Gi
