image:
  repository: 113504009718.dkr.ecr.us-east-1.amazonaws.com/ecr-repo-django
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false

config:
  POSTGRES_HOST: django-postgresql
  POSTGRES_PORT: 5432
  POSTGRES_DB: django_db
  POSTGRES_USER: django_user
  POSTGRES_PASSWORD: pass9764gd

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        postgresPassword: pass9764gd
        username: django_user
        database: django_db
        password: pass9764gd
  primary:
    persistence:
      size: 2Gi
